### PR TITLE
workaround for #26

### PR DESCRIPTION
**Pull request by balmas**
@PonteIneptique this is a bit of a hack, I'm just stripping unicode chars out of the branch name. I think this may be a github api bug, or else, I am just too stupid to figure out how to properly format the unicode for the put request.

### CODE REVIEW

**Comment by balmas** [comment]
I see I've broken the tests though through my use of encode, which now produces different hash keys :(

**Comment by PonteIneptique** [comment]
Let me see to that by tomorrow evening if you don't mind :)

2016-11-08 18:48 GMT+01:00 Bridget Almas <notifications@github.com>:

**Comment by balmas** [comment]
Yes, that's fine. I have updated the tests for now to work with my change (because I wanted to make sure I didn't really break anything, since I went ahead an put this change in production to enable finalization to happen for these repos), but I'm sure there's a better way to do this, I'm struggling with lack of knowledge about python and strings and unicode and bytes.

**Comment by PonteIneptique** [comment]
I was thinking about this :
http://stackoverflow.com/questions/5574042/string-slugification-in-python

2016-11-08 19:15 GMT+01:00 Coveralls <notifications@github.com>:

**Comment by balmas** [comment]
yes something like that would probably be a good solution

**Comment by PonteIneptique** [comment]
substituted by  #28

**Pull request closed without merging**
